-- First I need users in a seed
-- 2nd, I need to make these conform to the new data form I need


INSERT INTO events (title, description, name, date, location)
VALUES
("Wine Tasting", "Join us for a wine tasting event with cheese pairings", "John Doe", "03-12-22", "Miami"),
("Art in the Park", "Come enjoy local art and music in the park", "David Barcenas", "04-16-21", "San Francisco")

INSERT INTO events (title, description, name, date, location)
VALUES
("Wine Tasting", "Join us for a wine tasting event with cheese pairings", "John Doe", "03-12-22", "Miami"),
("Art in the Park", "Come enjoy local art and music in the park", "David Barcenas", "04-16-21", "San Francisco"),
("Paint Night", " BYOB paint night. All levels welcome.", "Jessica Smith", "06-23-22", "New York"),
("Cooking Class", "Learn to cook like a pro!", "Anne Nguyen", "09-01-21", "Boston"),
("Comedy Night", "Laugh the night away with local comics", "Mike Chang", "11-15-22", "Los Angeles"),
("Puppy Playtime", "Come play with adoptable puppies!", "John Doe", "03-12-22", "Miami"),
("Doggie Daycare", "Daycare for your furbabies!", "David Barcenas", "04-16-21", "San Francisco"),
("Dog Park", "Come socialize your pups!", "Jessica Smith", "06-23-22", "New York"),
("Cat Cafe", "Come hang out with adoptable cats!", "Anne Nguyen", "09-01-21", "Boston"),
("Yoga in the Park", "Start your day with some yoga in the park", "Mike Chang", "11-15-22", "Los Angeles"),
("Hiking", "Enjoy a day hike with friends!", "John Doe", "03-12-22", "Miami"),
("Picnic in the Park", "Pack a lunch and enjoy a day in the park", "David Barcenas", "04-16-21", "San Francisco"),
("Gardening Class", "Learn how to garden!", "Jessica Smith", "06-23-22", "New York"),
("Farmers Market", "Shop local and organic produce!", "Anne Nguyen", "09-01-21", "Boston"),
("Food Truck Festival", "Enjoy a variety of food trucks in one place", "Mike Chang", "11-15-22", "Los Angeles"),
("Museum Day", "Free admission to local museums!", "John Doe", "03-12-22", "Miami"),
("Symphony in the Park", "Enjoy a free symphony performance in the park", "David Barcenas", "04-16-21", "San Francisco"),
("Free Concert", "Enjoy a free concert in the park", "Jessica Smith", "06-23-22", "New York"),
("Open Mic Night", "Show off your talents at our open mic night!", "Anne Nguyen", "09-01-21", "Boston"),
("Trivia Night", "Test your knowledge at our trivia night!", "Mike Chang", "11-15-22", "Los Angeles"),
("Movie in the Park", "Enjoy a free movie in the park", "John Doe", "03-12-22", "Miami"),
("Bingo Night", "Come play bingo and win prizes!", "David Barcenas", "04-16-21", "San Francisco"),
("Karaoke Night", "Sing your heart out at our karaoke night!", "Jessica Smith", "06-23-22", "New York"),
("Book Club", "Come discuss the latest book with us!", "Anne Nguyen", "09-01-21", "Boston"),
("Game Night", "Come play games and meet new people!", "Mike Chang", "11-15-22", "Los Angeles"),
("Pottery Class", "Create something beautiful in our pottery class!", "John Doe", "03-12-22", "Miami"),
("Sewing Class", "Learn how to sew in our sewing class!", "David Barcenas", "04-16-21", "San Francisco"),
("Knitting Class", "Knit something cozy in our knitting class!", "Jessica Smith", "06-23-22", "New York"),
(" Painting Class", "Paint a masterpiece in our painting class!", "Anne Nguyen", "09-01-21", "Boston"),
("Dance Class", "Learn how to dance in our dance class!", "Mike Chang", "11-15-22", "Los Angeles"),
("Guitar Lessons", "Learn how to play guitar in our guitar lessons!", "John Doe", "03-12-22", "Miami"),
("Piano Lessons", "Learn how to play piano in our piano lessons!", "David Barcenas", "04-16-21", "San Francisco"),
("Singapore Cooking Class", "Learn how to cook Singaporean food in our cooking class!", "Jessica Smith", "06-23-22", "New York"),
("Thai Cooking Class", "Learn how to cook Thai food in our cooking class!", "Anne Nguyen", "09-01-21", "Boston"),
("Chinese Cooking Class", "Learn how to cook Chinese food in our cooking class!", "Mike Chang", "11-15-22", "Los Angeles"),
("Baking Class", "Learn how to bake in our baking class!", "John Doe", "03-12-22", "Miami"),
("Cake Decorating Class", "Learn how to decorate cakes in our cake decorating class!", "David Barcenas", "04-16-21", "San Francisco"),
("Ice Sculpting Class", "Learn how to sculpt ice in our ice sculpting class!", "Jessica Smith", "06-23-22", "New York"),
("Glassblowing Class", "Learn how to blow glass in our glassblowing class!", "Anne Nguyen", "09-01-21", "Boston"),
("Jewelry Making Class", "Learn how to make jewelry in our jewelry making class!", "Mike Chang", "11-15-22", "Los Angeles"),
("Photography Class", "Learn how to take great photos in our photography class!", "John Doe", "03-12-22", "Miami"),
("Screen Printing Class", "Learn how to screen print in our screen printing class!", "David Barcenas", "04-16-21", "San Francisco"),
("Woodworking Class", "Learn how to work with wood in our woodworking class!", "Jessica Smith", "06-23-22", "New York"),
("Origami Class", "Learn how to make origami in our origami class!", "Anne Nguyen", "09-01-21", "Boston"),
("Calligraphy Class", "Learn how to do calligraphy in our calligraphy class!", "Mike Chang", "11-15-22", "Los Angeles"),
("Languages Class", "Learn a new language in our languages class!", "John Doe", "03-12-22", "Miami"),
("Gardening Class", "Learn how to garden in our gardening class!", "David Barcenas", "04-16-21", "San Francisco"),
("Knitting Class", "Learn how to knit in our knitting class!", "Jessica Smith", "06-23-22", "New York"),
("Crocheting Class", "Learn how to crochet in our crocheting class!", "Anne Nguyen", "09-01-21", "Boston"),
("Macrame Class", "Learn how to make macrame in our macrame class!", "Mike Chang", "11-15-22", "Los Angeles"),
("Film Club", "Come watch and discuss films in our film club!", "John Doe", "03-12-22", "Miami"),
("Golf Club", "Come play golf with us in our golf club!", "David Barcenas", "04-16-21", "San Francisco"),
("Tennis Club", "Come play tennis with us in our tennis club!", "Jessica Smith", "06-23-22", "New York"),
("Bowling Club", "Come bowl with us in our bowling club!", "Anne Nguyen", "09-01-21", "Boston"),
("Chess Club", "Come play chess with us in our chess club!", "Mike Chang", "11-15-22", "Los Angeles"),
("Ping Pong Club", "Come play ping pong with us in our ping pong club!", "John Doe", "03-12-22", "Miami"),
("Pool Club", "Come play pool with us in our pool club!", "David Barcenas", "04-16-21", "San Francisco"),
("Running Club", "Come run with us in our running club!", "Jessica Smith", "06-23-22", "New York"),
("Hiking Club", "Come hike with us in our hiking club!", "Anne Nguyen", "09-01-21", "Boston"),
("Biking Club", "Come bike with us in our biking club!", "Mike Chang", "11-15-22", "Los Angeles")